### ISSUE TITLE
Sidemenu

### ISSUE THREAD

**Issue by Merlijnv** [EbenKouao/MMM-Face-Recognition-SMAI#1]
How do I get the sidemenu with add faceid

**Comment by EbenKouao** [comment]
Hi Merlijnv,

This side menu is a separate module. You could find this on the MagicMirror 3rd Party Module page too.
[https://github.com/EbenKouao/MMM-SmartTouch](https://github.com/EbenKouao/MMM-SmartTouch)

We'll put a full installation tutorial on YouTube next week. [Subscribe to keep updated.](https://www.youtube.com/watch?v=LI8b3kbzYoY)

Eben.

**Comment by Merlijnv** [comment]
Yeah I found that module but it only has 2 buttons and no config options

**Comment by EbenKouao** [comment]
This is the initial release. Added functionality would be released soon e.g. Home automation. As of now, the only customizable section is the position of the module. 
Feel free to fork the repo and customize it in the meanwhile.
