### ISSUE TITLE
 SMAI-face-dection.py

### ISSUE THREAD

**Issue by thetobyde** [EbenKouao/MMM-Face-Recognition-SMAI#3]
Hey there! I´ve got an prob.
Where can I find the  SMAI-face-dection.py? You said it is necessery to have these file to detect the face, but I can´t find it. Am I doing sthing wrong? 

Thx 4 help :)
Toby

**Comment by EbenKouao** [comment]
Hi thetobyde,
The MMM-Face-Recognition-SMAI.py has now been added to the Git Repo. The readme has been updated on where to copy it too. If you have any issues I would suggest trying out the already compiled Raspberry Pi Face Rec Image on [smartbuilds.io](https://smartbuilds.io), this would give a good idea on how the module works.
If you like the module, feel free to contribute and add more to it.

Thanks, 
Eben.

**Comment by thetobyde** [comment]
@EbenKouao ok Perfect. I would like to add some More, but cant find who the.py script starts. How is it started?
